ingress:
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: fifa-traefik.local
      frontendPaths:
        - path: /
          pathType: Prefix
      backendPaths:
        - path: /api
          pathType: Prefix
        - path: /ws
          pathType: Prefix
        - path: /healthz
          pathType: Prefix
        - path: /readyz
          pathType: Prefix
