apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fifa-wc-2026-card-trading.fullname" . }}-frontend
  labels:
    {{- include "fifa-wc-2026-card-trading.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "fifa-wc-2026-card-trading.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "fifa-wc-2026-card-trading.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- toYaml .Values.frontend.podLabels | nindent 8 }}
      annotations:
        {{- toYaml .Values.frontend.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fifa-wc-2026-card-trading.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
      volumes:
        - name: frontend-config
          configMap:
            name: {{ include "fifa-wc-2026-card-trading.fullname" . }}-config
            items:
              - key: config.js
                path: config.js
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
