apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fifa-wc-2026-card-trading.fullname" . }}-backend
  labels:
    {{- include "fifa-wc-2026-card-trading.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "fifa-wc-2026-card-trading.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "fifa-wc-2026-card-trading.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
        {{- toYaml .Values.backend.podLabels | nindent 8 }}
      annotations:
        {{- toYaml .Values.backend.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fifa-wc-2026-card-trading.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "fifa-wc-2026-card-trading.fullname" . }}-config
            - secretRef:
                name: {{ include "fifa-wc-2026-card-trading.secretName" . }}
          env:
            {{- range .Values.backend.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
