{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fifa-wc-2026-card-trading.fullname" . }}-backend
spec:
  minAvailable: {{ .Values.pdb.backend.minAvailable }}
  selector:
    matchLabels:
      {{- include "fifa-wc-2026-card-trading.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fifa-wc-2026-card-trading.fullname" . }}-frontend
spec:
  minAvailable: {{ .Values.pdb.frontend.minAvailable }}
  selector:
    matchLabels:
      {{- include "fifa-wc-2026-card-trading.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
