{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fifa-wc-2026-card-trading.secretName" . }}
  labels:
    {{- include "fifa-wc-2026-card-trading.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
{{- end }}
