apiVersion: v1
kind: Service
metadata:
  name: {{ include "fifa-wc-2026-card-trading.fullname" . }}-backend
  labels:
    {{- include "fifa-wc-2026-card-trading.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "fifa-wc-2026-card-trading.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
