{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fifa-wc-2026-card-trading.serviceAccountName" . }}
  labels:
    {{- include "fifa-wc-2026-card-trading.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
